routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//liste des rdv
Route::get('rendez_vous','ConsultationController@rendezVous')->name('rendez_vous');
Route::get('rdv','ConsultationController@rdv')->name('rdv');
Route::get('rdv/{id}/edit','ConsultationController@editRdv')->name('rdv_edit');
Route::put('rdv/{id}/update','ConsultationController@updateRdv')->name('rdv_update');

//get les constantes d'un patient

Route::get('/getConstante/{id}','PatientController@getConstante')->name('constante');

//get les consultations d'un patient

Route::get('/getConsultation/{id}','PatientController@getConsultation')->name('consultation');

//facturation

Route::get('consultation/{id}/facture','ConsultationController@facture')->name('facture');

//historique des prix de consultation
Route::get('/historique','TypeConsultationController@historique')->name('historique');

 //gestion du user  profil
    Route::get('/profil', 'ProfilController@index')->name('profil');
    Route::put('/profil/{id}/update', 'ProfilController@update')->name('profil.update');
    Route::post('/profil/change_password', 'ProfilController@change_password')->name('password');

// gestion ordonnance d'une consultation
Route::get('consultation/{id}/ordonnance','ConsultationController@ordonnance')->name('ordonnance');
Route::post('consultation/ordonnance','ConsultationController@postOrdonnance')->name('ordonnance_post');
Route::get('consultation/edit/{id}/ordonnance','ConsultationController@editOrdonnance')->name('ordonnance_edit');
Route::put('consultation/update/{id}/ordonnance','ConsultationController@updateOrdonnance')->name('ordonnance_update');
Route::get('consultation/delete/{id}/ordonnance','ConsultationController@destroyOrdonnance')->name('ordonnance_destroy');

//gestion soin d'une consultation
Route::get('consultation/{id}/soin','ConsultationController@soin')->name('soin');
Route::post('consultation/soin','ConsultationController@postSoin')->name('soin_post');
Route::get('consultation/edit/{id}/soin','ConsultationController@editSoin')->name('soin_edit');
Route::put('consultation/update/{id}/soin','ConsultationController@updateSoin')->name('soin_update');
Route::get('consultation/delete/{id}/soin','ConsultationController@destroySoin')->name('soin_destroy');


//gestion analyse d'une consultation
Route::get('consultation/{id}/analyse','ConsultationController@analyse')->name('analyse');
Route::post('consultation/analyse','ConsultationController@postAnalyse')->name('analyse_post');
Route::get('consultation/edit/{id}/analyse','ConsultationController@editAnalyse')->name('analyse_edit');
Route::put('consultation/update/{id}/analyse','ConsultationController@updateAnalyse')->name('analyse_update');
Route::get('consultation/delete/{id}/analyse','ConsultationController@destroyAnalyse')->name('analyse_destroy');

//liste des etats
Route::get('etat','ConsultationController@etat')->name('etat');
Route::post('consultation/date/pdf','ConsultationController@pdfConsultationParDate')->name('consultation_date_pdf');
Route::post('consultation/periode/pdf','ConsultationController@pdfConsultationParPeriode')->name('consultation_periode_pdf');
Route::post('patient/periode/pdf','PatientController@pdfPatientParPeriode')->name('patient_periode_pdf');
Route::post('consultation/patient/pdf','ConsultationController@pdfConsultationParPatient')->name('consultation_patient_pdf');
Route::post('consultation/patient/periode/pdf','ConsultationController@pdfConsultationParPatientPeriode')->name('consultation_patient_periode_pdf');
Route::post('consultation/ordonnance/pdf','ConsultationController@pdfOrdonnance')->name('consultation_ordonnance_pdf');
Route::get('consultation/{id}/facture/pdf','ConsultationController@pdfFacture')->name('consultation_facture_pdf');

Route::resource('role','RoleController');
Route::resource('permission','PermissionController');
Route::resource('medecin','MedecinController');
Route::get('medecin/destroy/{id}','MedecinController@destroy');
Route::resource('infirmiere','InfirmiereController');
Route::get('infirmiere/destroy/{id}','InfirmiereController@destroy');
Route::resource('secretaire','SecretaireController');
Route::get('secretaire/destroy/{id}','SecretaireController@destroy');
Route::resource('patient','PatientController');
Route::get('patient/destroy/{id}','PatientController@destroy');
// Route::resource('antecedent','AntecedentController');
// Route::resource('technicien','TechnicienController');
Route::resource('consultation','ConsultationController');
Route::get('consultation/destroy/{id}','ConsultationController@destroy');
Route::resource('constante','ConstanteController');
Route::get('constante/destroy/{id}','ConstanteController@destroy');
Route::resource('typeConsultation','TypeConsultationController');
Route::get('typeConsultation/destroy/{id}','TypeConsultationController@destroy');
// Route::resource('typeAntecedent','TypeAntecedentController');
Route::resource('soin','SoinController');
Route::get('soin/destroy/{id}','SoinController@destroy');
Route::resource('analyse','AnalyseController');
Route::get('analyse/destroy/{id}','AnalyseController@destroy');
Route::resource('produit','ProduitController');
Route::get('produit/destroy/{id}','ProduitController@destroy');
Route::resource('medicament','MedicamentController');
Route::get('medicament/destroy/{id}','MedicamentController@destroy');


// Route::resource('user','UserController');
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Medecin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Medecin extends User
{
	public function user()
	{
		return $this->morphOne(User::class,'userable');
	}
        
	 public function consultations()
    {
    	return $this->hasMany(Consultation::class);
    }
    
     public function patients()
    {
        return $this->belongsToMany(Patient::class)->withPivot('date','heure','objet')->withTimestamps();

    }
}

app/Http/Controllers/MedecinController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Medecin;
use App\User;
use App\Role;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;
use Hash;
use DB;
use Auth;

class MedecinController extends Controller
{
      public function __construct()
    {
        $this->middleware('auth');

        // $this->middleware('permission:medecin-list|medecin-create|medecin-edit|medecin-delete', ['only' => ['index','store']]);
        // $this->middleware('permission:medecin-create', ['only' => ['create','store']]);

        // $this->middleware('permission:medecin-edit', ['only' => ['edit','update']]);
 
        // $this->middleware('permission:medecin-delete', ['only' => ['destroy']]);

    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
 

    public function index()
    {
         $medecins = Medecin::get();

        return view('medecins/index',compact('medecins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $medecins = Medecin::get();
         $roles= Role::pluck('name','id');

        return view('medecins/create',compact('roles','medecins'));
    }
    

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        // $inputs = array_merge($request->all(),['password'=>Hash::make($request->password)]);
         // $medecin = new Medecin();
         // $medecin->save();

        $medecin = Medecin::create();

         $user = $request->all();
         $user['password']= bcrypt($request->password);
         $medecin->user()->create($user);

         return redirect(route('medecin.create', $medecin))->withInfo('Enregistrement réussi');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $medecin= Medecin::findOrFail($id);

         $roles= Role::pluck('name','id');

        return view('medecins/show',compact('medecin','roles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $medecin= Medecin::findOrFail($id);
         $roles= Role::pluck('name','id');

        return view('medecins/edit',compact('medecin','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, $id)
    {
         $medecin = Medecin::findOrfail($id);

         $user = User::where('userable_id',$id)->get();

         // $user = $request->except('_method','_token');

         if(empty($request->password))
         {
            $medecin->user->password = $medecin->user->password;
         }

         $medecin->user->username = $request->username;
         $medecin->user->firstname = $request->firstname;
         $medecin->user->lastname = $request->lastname;
         $medecin->user->status = 'active';
         $medecin->user->sexe = $request->sexe;
         $medecin->user->phone = $request->phone;
         $medecin->user->address = $request->address;
         $medecin->user->role = $request->role;
         $medecin->user->password = bcrypt($request->password);
         $medecin->user->userable_id = $id;
         $medecin->user->userable_type ='App\Medecin';
         $medecin->user->save();

         // $medecin->user()->update($user);

        return redirect(route('medecin.create', $id))->withSuccess('modification réussi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $medecin = Medecin::findOrfail($id);

        $medecins = DB::table('consultations')->where('userable_id',$id)->get();

         $nb = count($medecins);

         if($nb>0)
         {
             return redirect(route('typeConsultation.create', $medecin))->withDanger(' Vous ne pouvez pas supprimez cet enregistrement car il est utilisé au niveau d\'une consultation');

         }


        $medecin->user()->delete();

        $medecin->delete();

        return redirect(route('medecin.create', $id))->withDanger('Suppression réussi');
    }


}

resources/views/medecins/create.blade.php
@extends("template")
  
  @section('content')

  @include('flash')

  <div class="row">
          <div class="col-md-12">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Créer</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                {!!Form::open(['method'=>'POST', 'url'=>route('medecin.store')]) !!}

                  <div class="box-body">

                         <div class="form-group col-md-4 {!! $errors->has('lastname')?'has-error': '' !!}">
                         {!!Form::label('lastname','nom')  !!}
                         {!! Form::text('lastname',null, ['class'=>'form-control','id'=>'lastname','placeholder'=>'']) !!}
                         {!! $errors->first('lastname','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>
                         
                         <div class="form-group col-md-4 {!! $errors->has('firstname')?'has-error': '' !!}">
                            {!!Form::label('firstname','prénom')!!}
                            {!! Form::text('firstname',null, ['class'=>'form-control','id'=>'firstname','placeholder'=>'']) !!}
                            {!! $errors->first('firstname','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                          <div class="form-group col-md-4 {!! $errors->has('sexe')?'has-error': '' !!}">

                         {!!Form::label('sexe','sexe')!!}
                         {!! Form::select('sexe',['M'=>'masculin','F'=>'feminin'],null, ['class'=>'form-control','id'=>'sexe']) !!}

                         {!! $errors->first('sexe','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                         <div class="form-group col-md-4 {!! $errors->has('phone')?'has-error': '' !!}">
                            {!!Form::label('phone','téléphone')!!}
                            {!! Form::text('phone',null, ['class'=>'form-control','id'=>'phone','placeholder'=>'Exemple:22-25-91-20 ou 90-32-58-42']) !!}
                            {!! $errors->first('phone','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>
                         <div class="form-group col-md-4 {!! $errors->has('email')?'has-error': '' !!}">
                            {!!Form::label('email','email')!!}
                            {!! Form::email('email',null, ['class'=>'form-control','id'=>'email','placeholder'=>' Exemple:tademanao92.ot@gmail.com']) !!}
                            {!! $errors->first('email','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                         <div class="form-group col-md-4 {!! $errors->has('username')?'has-error': '' !!}">
                            {!!Form::label('username','nom utilisateur')!!}
                            {!! Form::text('username',null, ['class'=>'form-control','id'=>'username','placeholder'=>'']) !!}
                            {!! $errors->first('username','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                          <div class="form-group col-md-4 {!! $errors->has('address')?'has-error': '' !!}">
                            {!!Form::label('address','adresse')!!}
                            {!! Form::text('address',null, ['class'=>'form-control','id'=>'address','placeholder'=>'', 'row'=>8]) !!}
                            {!! $errors->first('address','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>
                          <div class="form-group col-md-4 {!! $errors->has('sexe')?'has-error': '' !!}">
                           {!!Form::label('role','role')!!}
                           {!! Form::select('role',['Admin'=>'Admin','Médecin'=>'Médecin','Secrétaire'=>'Secrétaire','Infirmière'=>'Infirmière'],null, ['class'=>'form-control','id'=>'sexe']) !!}

                           {!! $errors->first('role','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                           <div class="form-group col-md-4 {!! $errors->has('password')?'has-error': '' !!}">
                            {!!Form::label('password','mot de passe')!!}
                            {!! Form::password('password', ['class'=>'form-control','id'=>'password','placeholder'=>'', 'row'=>8]) !!}
                            {!! $errors->first('password','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                          <div class="form-group col-md-4">
                            {!!Form::label('password-confirm','confirmation de mot de passe')!!}
                            {!! Form::password('password_confirmation', ['class'=>'form-control','id'=>'password-confirm', 'row'=>8]) !!}
                          </div>     

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Envoyer</button>
                  </div>

                  {!! Form::close() !!}
              </div><!-- /.box -->
                  
          </div>

          <div class="col-md-12">
            <div class="box box-primary">
                  <div class="box-header">
                    <h3 class="box-title">Liste des médecins</h3>
                  </div><!-- /.box-header -->
                  <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                      <thead>
                        <tr>
                           <th>Code</th>
                           <th>Nom</th>
                           <th>Prénoms</th>
                           <th>Téléphone</th>
                           <th>Email</th>
                           <th>Nom Utilisateur</th>
                           <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                       
                      
                    @foreach($medecins as $medecin) 

                      <tr> 
                           <td>{{ $medecin->id }}</td>
                           <td>{{ $medecin->user->lastname }}</td>
                           <td>{{ $medecin->user->firstname }}</td>
                           <td>{{ $medecin->user->phone }}</td>
                           <td>{{ $medecin->user->email }}</td>
                           <td>{{ $medecin->user->username }}</td>
                           
                           <td><a class="btn btn-xs btn-primary" href="{{ route('medecin.show',$medecin) }}">Détail</a>
                            <a class="btn btn-xs btn-warning" href="{{ route('medecin.edit',$medecin) }}">Editer</a>
                            <a class="btn btn-xs btn-danger" href="{{URL::to('/medecin/destroy/'.$medecin->id) }}" onclick="return confirm(' Voulez-vous Vraiment supprimer cet enregistrement?')">Supprimer</a>
                           </td>
                      </tr>
                      @endforeach
                      </tbody>
                       <tfoot>
                        <tr>
                           <th>Code</th>
                           <th>Nom</th>
                           <th>Prénoms</th>
                           <th>Téléphone</th>
                           <th>Email</th>
                           <th>Nom Utilisateur</th>
                           <th>Actions</th>
                        </tr>
                      </tfoot>
                    </table>
                  </div><!-- /.box-body -->
            </div><!-- /.box -->  
          </div>

         
  
  </div>

  

 

     
@stop

resources/views/medecins/edit.blade.php
@extends("template")
  
  @section('content')
  
  @include('flash')

  <div class="row">
          <div class="col-md-12">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Editer</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                {!!Form::open(['method'=>'put', 'url'=>route('medecin.update',$medecin)]) !!}

                  <div class="box-body">
                        
                         <div class="form-group col-md-4 {!! $errors->has('lastname')?'has-error': '' !!}">
                         {!!Form::label('lastname','nom')  !!}
                         {!! Form::text('lastname', $medecin->user->lastname, ['class'=>'form-control','id'=>'lastname','placeholder'=>'lastname']) !!}
                         {!! $errors->first('lastname','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>
                         
                         <div class="form-group col-md-4 {!! $errors->has('firstname')?'has-error': '' !!}">
                            {!!Form::label('firstname','prénom')!!}
                            {!! Form::text('firstname',$medecin->user->firstname, ['class'=>'form-control','id'=>'firstname','placeholder'=>'firstnames']) !!}
                            {!! $errors->first('firstname','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                           <div class="form-group col-md-4 {!! $errors->has('sexe')?'has-error': '' !!}">

                         {!!Form::label('sexe','sexe')!!}
                         {!! Form::select('sexe',['M'=>'masculin','F'=>'feminin'],$medecin->user->sexe, ['class'=>'form-control','id'=>'sexe']) !!}

                         {!! $errors->first('sexe','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                         <div class="form-group col-md-4 {!! $errors->has('phone')?'has-error': '' !!}">
                            {!!Form::label('phone','téléphone')!!}
                            {!! Form::text('phone',$medecin->user->phone, ['class'=>'form-control','id'=>'phone','placeholder'=>'Téléphone']) !!}
                            {!! $errors->first('phone','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>
                         <div class="form-group col-md-4 {!! $errors->has('email')?'has-error': '' !!}">
                            {!!Form::label('email','email')!!}
                            {!! Form::email('email',$medecin->user->email, ['class'=>'form-control','id'=>'email','placeholder'=>'Email']) !!}
                            {!! $errors->first('email','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                         <div class="form-group col-md-4 {!! $errors->has('username')?'has-error': '' !!}">
                            {!!Form::label('username','nom utilisateur')!!}
                            {!! Form::text('username',$medecin->user->username, ['class'=>'form-control','id'=>'username','placeholder'=>'username']) !!}
                            {!! $errors->first('username','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                          <div class="form-group col-md-4 {!! $errors->has('address')?'has-error': '' !!}">
                            {!!Form::label('address','adresse')!!}
                            {!! Form::text('address',$medecin->user->address, ['class'=>'form-control','id'=>'address','placeholder'=>'address', 'row'=>8]) !!}
                            {!! $errors->first('address','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                           <div class="form-group col-md-4 {!! $errors->has('sexe')?'has-error': '' !!}">
                           {!!Form::label('role','role')!!}
                           {!! Form::select('role',['Admin'=>'Admin','Médecin'=>'Médecin','Secrétaire'=>'Secrétaire','Infirmière'=>'Infirmière'],$medecin->user->role, ['class'=>'form-control','id'=>'sexe']) !!}

                           {!! $errors->first('role','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                          <div class="form-group col-md-4 {!! $errors->has('password')?'has-error': '' !!}">
                            {!!Form::label('password','mot de passe')!!}
                            {!! Form::password('password', ['class'=>'form-control','id'=>'password','placeholder'=>'', 'row'=>8]) !!}
                            {!! $errors->first('password','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Envoyer</button> <a class="btn btn-primary" href="{{ route('medecin.create',$medecin) }}">Retour</a>
                  </div>

                  {!! Form::close() !!}
              </div><!-- /.box -->
                  
          </div>
  
  </div>

@stop

resources/views/medecins/index.blade.php
@extends("adminTemplate")
  
  @section('content')
  @include('flash')
  
   <div class="col-md-12">
          <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Liste des membres</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                          <th>Code</th>
                         <th>nom</th>
                         <th>prenom</th>
                         <th>telephone</th>
                         <th>sexe</th>
                         <th>Modifier</th>
                         <th>Supprimer</th>
                      </tr>
                      </tr>
                    </thead>
                    <tbody>
                     
                   @foreach($membres as $membre) 

                    <tr> 

                         <td>{{ $membre->id }}</td>
                         <td>{{ $membre->nom}}</td>
                         <td>{{ $membre->prenom}}</td>
                         <td>{{ $membre->sexe}}</td>
                         <td>{{ $membre->tel}}</td>
                         
                      

                        <td><a class="btn btn-primary" href="{{ route('membre.edit',$membre) }}">Editer <i class="fa fa-edit"></i></a> </td>
                         
                          {{Form::open(['method'=>'delete', 'url'=>route('membre.destroy',$membre)]) }}
                          <td>
                          <button class="btn btn-danger" onclick="return confirm(' Voulez-vous Vraiment supprimer cet enregistrement?')" >Supprimer<i class="fa fa-trash"></i></button>
                          </td>
                            {!! Form::close() !!}
                    </tr>
                    @endforeach
                    </tbody>
                     <tfoot>
                      <tr>
                         <th>Code</th>
                         <th>nom</th>
                         <th>prenom</th>
                         <th>telephone</th>
                         <th>sexe</th>
                         <th>Modifier</th>
                         <th>Supprimer</th>
                      </tr>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->  
     </div>
</div>       
     
@stop

resources/views/medecins/show.blade.php
@extends("template")
  
  @section('content')
  
  @include('flash')

  <div class="row">
          <div class="col-md-12">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Détail</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                {!!Form::open(['method'=>'put', 'url'=>route('medecin.update',$medecin)]) !!}

                  <div class="box-body">
                        
                         <div class="form-group col-md-4 {!! $errors->has('lastname')?'has-error': '' !!}">
                         {!!Form::label('lastname','nom')  !!}
                         {!! Form::text('lastname', $medecin->user->lastname, ['class'=>'form-control','id'=>'lastname','placeholder'=>'lastname','readOnly'=>'readOnly']) !!}
                         {!! $errors->first('lastname','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>
                         
                         <div class="form-group col-md-4 {!! $errors->has('firstname')?'has-error': '' !!}">
                            {!!Form::label('firstname','prénom')!!}
                            {!! Form::text('firstname',$medecin->user->firstname, ['class'=>'form-control','id'=>'firstname','placeholder'=>'firstnames','readOnly'=>'readOnly']) !!}
                            {!! $errors->first('firstname','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                           <div class="form-group col-md-4 {!! $errors->has('sexe')?'has-error': '' !!}">

                         {!!Form::label('sexe','sexe')!!}
                         {!! Form::select('sexe',['M'=>'masculin','F'=>'feminin'],$medecin->user->sexe, ['class'=>'form-control','id'=>'sexe','readOnly'=>'readOnly']) !!}

                         {!! $errors->first('sexe','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                         <div class="form-group col-md-4 {!! $errors->has('phone')?'has-error': '' !!}">
                            {!!Form::label('phone','téléphone')!!}
                            {!! Form::text('phone',$medecin->user->phone, ['class'=>'form-control','id'=>'phone','placeholder'=>'Téléphone','readOnly'=>'readOnly']) !!}
                            {!! $errors->first('phone','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>
                         <div class="form-group col-md-4 {!! $errors->has('email')?'has-error': '' !!}">
                            {!!Form::label('email','email')!!}
                            {!! Form::email('email',$medecin->user->email, ['class'=>'form-control','id'=>'email','placeholder'=>'Email','readOnly'=>'readOnly']) !!}
                            {!! $errors->first('email','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                         <div class="form-group col-md-4 {!! $errors->has('username')?'has-error': '' !!}">
                            {!!Form::label('username','nom utilisateur')!!}
                            {!! Form::text('username',$medecin->user->username, ['class'=>'form-control','id'=>'username','placeholder'=>'username','readOnly'=>'readOnly']) !!}
                            {!! $errors->first('username','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                          <div class="form-group col-md-4 {!! $errors->has('address')?'has-error': '' !!}">
                            {!!Form::label('address','adresse')!!}
                            {!! Form::text('address',$medecin->user->address, ['class'=>'form-control','id'=>'address','placeholder'=>'address', 'row'=>8,'readOnly'=>'readOnly']) !!}
                            {!! $errors->first('address','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                          <div class="form-group col-md-4 {!! $errors->has('sexe')?'has-error': '' !!}">
                             {!!Form::label('role','role')!!}
                             {!! Form::select('role',['Admin'=>'Admin','Médecin'=>'Médecin','Secrétaire'=>'Secrétaire','Infirmière'=>'Infirmière'],null, ['class'=>'form-control','id'=>'sexe','readOnly'=>'readOnly']) !!}

                             {!! $errors->first('role','<small class="help-block"><strong>:message</strong></small>') !!}
                          </div>

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                   <a class="btn btn-primary" href="{{ route('medecin.create',$medecin) }}">Retour</a>
                  </div>

                  {!! Form::close() !!}
              </div><!-- /.box -->
                  
          </div>
  
  </div>

@stop