routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//liste des rdv
Route::get('rendez_vous','ConsultationController@rendezVous')->name('rendez_vous');
Route::get('rdv','ConsultationController@rdv')->name('rdv');
Route::get('rdv/{id}/edit','ConsultationController@editRdv')->name('rdv_edit');
Route::put('rdv/{id}/update','ConsultationController@updateRdv')->name('rdv_update');

//get les constantes d'un patient

Route::get('/getConstante/{id}','PatientController@getConstante')->name('constante');

//get les consultations d'un patient

Route::get('/getConsultation/{id}','PatientController@getConsultation')->name('consultation');

//facturation

Route::get('consultation/{id}/facture','ConsultationController@facture')->name('facture');

//historique des prix de consultation
Route::get('/historique','TypeConsultationController@historique')->name('historique');

 //gestion du user  profil
    Route::get('/profil', 'ProfilController@index')->name('profil');
    Route::put('/profil/{id}/update', 'ProfilController@update')->name('profil.update');
    Route::post('/profil/change_password', 'ProfilController@change_password')->name('password');

// gestion ordonnance d'une consultation
Route::get('consultation/{id}/ordonnance','ConsultationController@ordonnance')->name('ordonnance');
Route::post('consultation/ordonnance','ConsultationController@postOrdonnance')->name('ordonnance_post');
Route::get('consultation/edit/{id}/ordonnance','ConsultationController@editOrdonnance')->name('ordonnance_edit');
Route::put('consultation/update/{id}/ordonnance','ConsultationController@updateOrdonnance')->name('ordonnance_update');
Route::get('consultation/delete/{id}/ordonnance','ConsultationController@destroyOrdonnance')->name('ordonnance_destroy');

//gestion soin d'une consultation
Route::get('consultation/{id}/soin','ConsultationController@soin')->name('soin');
Route::post('consultation/soin','ConsultationController@postSoin')->name('soin_post');
Route::get('consultation/edit/{id}/soin','ConsultationController@editSoin')->name('soin_edit');
Route::put('consultation/update/{id}/soin','ConsultationController@updateSoin')->name('soin_update');
Route::get('consultation/delete/{id}/soin','ConsultationController@destroySoin')->name('soin_destroy');


//gestion analyse d'une consultation
Route::get('consultation/{id}/analyse','ConsultationController@analyse')->name('analyse');
Route::post('consultation/analyse','ConsultationController@postAnalyse')->name('analyse_post');
Route::get('consultation/edit/{id}/analyse','ConsultationController@editAnalyse')->name('analyse_edit');
Route::put('consultation/update/{id}/analyse','ConsultationController@updateAnalyse')->name('analyse_update');
Route::get('consultation/delete/{id}/analyse','ConsultationController@destroyAnalyse')->name('analyse_destroy');

//liste des etats
Route::get('etat','ConsultationController@etat')->name('etat');
Route::post('consultation/date/pdf','ConsultationController@pdfConsultationParDate')->name('consultation_date_pdf');
Route::post('consultation/periode/pdf','ConsultationController@pdfConsultationParPeriode')->name('consultation_periode_pdf');
Route::post('patient/periode/pdf','PatientController@pdfPatientParPeriode')->name('patient_periode_pdf');
Route::post('consultation/patient/pdf','ConsultationController@pdfConsultationParPatient')->name('consultation_patient_pdf');
Route::post('consultation/patient/periode/pdf','ConsultationController@pdfConsultationParPatientPeriode')->name('consultation_patient_periode_pdf');
Route::post('consultation/ordonnance/pdf','ConsultationController@pdfOrdonnance')->name('consultation_ordonnance_pdf');
Route::get('consultation/{id}/facture/pdf','ConsultationController@pdfFacture')->name('consultation_facture_pdf');

Route::resource('role','RoleController');
Route::resource('permission','PermissionController');
Route::resource('medecin','MedecinController');
Route::get('medecin/destroy/{id}','MedecinController@destroy');
Route::resource('infirmiere','InfirmiereController');
Route::get('infirmiere/destroy/{id}','InfirmiereController@destroy');
Route::resource('secretaire','SecretaireController');
Route::get('secretaire/destroy/{id}','SecretaireController@destroy');
Route::resource('patient','PatientController');
Route::get('patient/destroy/{id}','PatientController@destroy');
// Route::resource('antecedent','AntecedentController');
// Route::resource('technicien','TechnicienController');
Route::resource('consultation','ConsultationController');
Route::get('consultation/destroy/{id}','ConsultationController@destroy');
Route::resource('constante','ConstanteController');
Route::get('constante/destroy/{id}','ConstanteController@destroy');
Route::resource('typeConsultation','TypeConsultationController');
Route::get('typeConsultation/destroy/{id}','TypeConsultationController@destroy');
// Route::resource('typeAntecedent','TypeAntecedentController');
Route::resource('soin','SoinController');
Route::get('soin/destroy/{id}','SoinController@destroy');
Route::resource('analyse','AnalyseController');
Route::get('analyse/destroy/{id}','AnalyseController@destroy');
Route::resource('produit','ProduitController');
Route::get('produit/destroy/{id}','ProduitController@destroy');
Route::resource('medicament','MedicamentController');
Route::get('medicament/destroy/{id}','MedicamentController@destroy');


// Route::resource('user','UserController');
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
     protected $fillable = [
        'name'
    ];

     public function permissions()
    {
    	return $this->belongsToMany(Permission::class)->withTimestamps();

    }

    //  public function users()
    // {
    //     return $this->HasMany(User::class);
    // }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permission;
use App\Role;
use \DB;

class RoleController extends Controller
{

     public function __construct()
    {
        $this->middleware('auth');

        // $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
        // $this->middleware('permission:role-create', ['only' => ['create','store']]);

        // $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
 
        // $this->middleware('permission:role-delete', ['only' => ['destroy']]);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

      /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
         $roles = Role::get();

         $permissions = Permission::get();

        return view('roles/create', compact('roles','permissions'));


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $role = Role::create($request->all());

          // Creation du role
            $role = new Role();

            $role->name = $request->name;
            $role->save();

            // liaison role des permissions
            $permissions = $request->permissions;

            $role->permissions()->attach($permissions);

        return redirect(route('role.create', $role))->withInfo('Enregistrement réussi');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $role = Role::find($id);

         $rolePermissions = Permission::join("permission_role","permission_role.permission_id","=","permissions.id")

            ->where("permission_role.role_id",$id)

            ->get();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //  $role= Role::findOrFail($id);

        //  $permissions= Permission::pluck('libelle','id');

        // return view('roles/edit',compact('role','permissions'));

        $role= Role::findOrFail($id);

        $permissions = Permission::get();

         $rolePermissions = DB::table("permission_role")->where("permission_role.role_id",$id)

            ->pluck('permission_role.permission_id','permission_role.permission_id')

            ->all();

        // $rolePermissions = $role->permissions;



        return view('roles/edit',compact('role','permissions','rolePermissions'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $role = Role::findOrfail($id);

        // $role->update($request->all());


        $role = Role::findOrfail($id);

        $role->name = $request->input('name');

        $role->save();

        $role->permissions()->sync($request->input('permissions'));

      return redirect(route('role.create', $id))->withSuccess('modification réussi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrfail($id);

        $permissions = $role->permissions;

        $role->permissions()->detach($permissions);

        $role->delete();

        return redirect(route('role.create', $id))->withDanger('Suppression réussi');
    }
}

resources/views/roles/create.blade.php
@extends("template")
  
  @section('content')

  @include('flash')

  <div class="row">
          <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Créer</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                {!!Form::open(['method'=>'POST', 'url'=>route('role.store')]) !!}

                  <div class="box-body">

                         <div class="form-group col-md-6 {!! $errors->has('name')?'has-error': '' !!}">
                         {!!Form::label('name','name')  !!}
                         {!! Form::text('name',null, ['class'=>'form-control','id'=>'name','placeholder'=>'']) !!}
                         {!! $errors->first('name','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>
                        

                       
                          <div class="col-xs-12 col-sm-12 col-md-12">

                           <!--  <div class="form-group">

                                <strong>Permissions:</strong>

                                <br/>

                                @foreach($permissions as $value)

                                    <label>{{ Form::checkbox('permissions[]', $value->id, false, array('class' => 'name')) }}

                                    {{ $value->name }}</label>

                                <br/>

                                @endforeach

                            </div> -->

                          </div>

                       <table id="example1" class="table table-bordered table-striped">
                          <thead>
                            <tr>
                               <th>Libelle</th>
                               <th></th>
                             
                            </tr>
                          </thead>
                          <tbody> 
                            @foreach($permissions as $value) 

                              <tr> 
                                   <td>{{ $value->name }}</td>
                                   <td>{{ Form::checkbox('permissions[]', $value->id, false, array('class' => 'name')) }}</td>
                              </tr>
                              @endforeach
                          </tbody>
                          <tfoot>
                            <tr>
                              <th>Libelle</th>
                              <th></th>
                            </tr>
                          </tfoot>
                       </table>

                          

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Envoyer</button>
                  </div>

                  {!! Form::close() !!}
              </div><!-- /.box -->
                  
          </div>

          <div class="col-md-12">
            <div class="box box-primary">
                  <div class="box-header">
                    <h3 class="box-title">Liste des roles</h3>
                  </div><!-- /.box-header -->
                  <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                      <thead>
                        <tr>
                           <th>Code</th>
                           <th>name</th>
                           <th>modifier</th>
                           <th>supprimer</th>
                        </tr>
                      </thead>
                      <tbody>
                       
                      
                    @foreach($roles as $role) 

                      <tr> 
                           <td>{{ $role->id }}</td>
                           <td>{{ $role->name }}</td>
                  

                           <td><a class="btn btn-primary" href="{{ route('role.edit',$role) }}">Editer</a></td>
                           <td>
                            {{Form::open(['method'=>'delete', 'url'=>route('role.destroy',$role)]) }}
    
                            <button class="btn btn-danger" onclick="return confirm(' Voulez-vous Vraiment supprimer cet enregistrement?')" >Supprimer</button>
                              {!! Form::close() !!}
                           </td>
                      </tr>
                      @endforeach
                      </tbody>
                       <tfoot>
                        <tr>
                          <th>Code</th>
                           <th>name</th>
                           <th>modifier</th>
                           <th>supprimer</th>
                        </tr>
                      </tfoot>
                  </table>
                  </div><!-- /.box-body -->
            </div><!-- /.box -->  
          </div>

         
  
  </div>

  

 

     
@stop

resources/views/roles/edit.blade.php
@extends("template")
  
  @section('content')

  @include('flash')

  <div class="row">
          <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Créer</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                {!!Form::open(['method'=>'PUT', 'url'=>route('role.update',$role)]) !!}

                  <div class="box-body">

                         <div class="form-group col-md-6 {!! $errors->has('name')?'has-error': '' !!}">
                         {!!Form::label('name','name')  !!}
                         {!! Form::text('name',$role->name, ['class'=>'form-control','id'=>'name','placeholder'=>'']) !!}
                         {!! $errors->first('name','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>
                        

                       
                       <div class="col-xs-12 col-sm-12 col-md-12">

                          <!-- <div class="form-group">

                              <strong>Permission:</strong>

                              <br/>

                              @foreach($permissions as $value)

                                  <label>{{ Form::checkbox('permissions[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}

                                  {{ $value->name }}</label>

                              <br/>

                              @endforeach

                          </div> -->

                       </div>

                       <table id="example1" class="table table-bordered table-striped">
                          <thead>
                            <tr>
                               <th>Libelle</th>
                               <th></th>
                             
                            </tr>
                          </thead>
                          <tbody> 
                            @foreach($permissions as $value) 

                              <tr> 
                                   <td>{{ $value->name }}</td>
                                   <td>{{ Form::checkbox('permissions[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}</td>
                              </tr>
                              @endforeach
                          </tbody>
                          <tfoot>
                            <tr>
                              <th>Libelle</th>
                              <th></th>
                            </tr>
                          </tfoot>
                       </table>

                          

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Envoyer</button>
                  </div>

                  {!! Form::close() !!}
              </div><!-- /.box -->
                  
          </div>
         
  </div>

  

 

     
@stop

resources/views/roles/form.blade.php
<?php

if(!isset($soin->id)){
	$options = ['method'=>'post','url'=>action('SoinController@store')];
	
} else{

	$options = ['method'=>'put','url'=>action('SoinController@update',$soin)];
}

?>

@include('flash')

<div class="row">
          <div class="col-md-12">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Créer</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                {!!Form::open($options)!!}

                  <div class="box-body">
                  			
                         <div class="form-group col-md-6 {!! $errors->has('libelle')?'has-error': '' !!}">
                         {!!Form::label('libelle','libelle')  !!}
                         {!! Form::text('libelle', $soin->libelle, ['class'=>'form-control','id'=>'libelle','placeholder'=>'libelle']) !!}
                         {!! $errors->first('libelle','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>
                         
                         <div class="form-group col-md-6 {!! $errors->has('prix_unitaire')?'has-error': '' !!}">
                            {!!Form::label('prix_unitaire','prix_unitaire')!!}
                            {!! Form::text('prix_unitaire',$soin->prix_unitaire, ['class'=>'form-control','id'=>'prix_unitaire','placeholder'=>'prix_unitaires']) !!}
                            {!! $errors->first('prix_unitaire','<small class="help-block"><strong>:message</strong></small>') !!}
                         </div>

                          
                       

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Envoyer</button>
                  </div>

                  {!! Form::close() !!}
              </div><!-- /.box -->
                  
          </div>
  
  </div>

resources/views/roles/index.blade.php
@extends("adminTemplate")
  
  @section('content')
  @include('flash')
  
   <div class="col-md-12">
          <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Liste des membres</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                          <th>Code</th>
                         <th>nom</th>
                         <th>prenom</th>
                         <th>telephone</th>
                         <th>sexe</th>
                         <th>Modifier</th>
                         <th>Supprimer</th>
                      </tr>
                      </tr>
                    </thead>
                    <tbody>
                     
                   @foreach($membres as $membre) 

                    <tr> 

                         <td>{{ $membre->id }}</td>
                         <td>{{ $membre->nom}}</td>
                         <td>{{ $membre->prenom}}</td>
                         <td>{{ $membre->sexe}}</td>
                         <td>{{ $membre->tel}}</td>
                         
                      

                        <td><a class="btn btn-primary" href="{{ route('membre.edit',$membre) }}">Editer <i class="fa fa-edit"></i></a> </td>
                         
                          {{Form::open(['method'=>'delete', 'url'=>route('membre.destroy',$membre)]) }}
                          <td>
                          <button class="btn btn-danger" onclick="return confirm(' Voulez-vous Vraiment supprimer cet enregistrement?')" >Supprimer<i class="fa fa-trash"></i></button>
                          </td>
                            {!! Form::close() !!}
                    </tr>
                    @endforeach
                    </tbody>
                     <tfoot>
                      <tr>
                         <th>Code</th>
                         <th>nom</th>
                         <th>prenom</th>
                         <th>telephone</th>
                         <th>sexe</th>
                         <th>Modifier</th>
                         <th>Supprimer</th>
                      </tr>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->  
     </div>
</div>       
     
@stop